'use strict';

const DEPLOYMENT_STATES = Object.freeze({
  EMPTY: 'EMPTY',
  REVIEWING_REQUEST: 'REVIEWING_REQUEST',
  ASKING_CLARIFYING_QUESTION: 'ASKING_CLARIFYING_QUESTION',
  READY_TO_GENERATE: 'READY_TO_GENERATE',
  GENERATING: 'GENERATING',
  GENERATED: 'GENERATED',
  PREFLIGHT_RUNNING: 'PREFLIGHT_RUNNING',
  PREFLIGHT_FAILED: 'PREFLIGHT_FAILED',
  DRY_RUN_RUNNING: 'DRY_RUN_RUNNING',
  DRY_RUN_FAILED: 'DRY_RUN_FAILED',
  AUTO_REPAIRING: 'AUTO_REPAIRING',
  NEEDS_USER_INPUT: 'NEEDS_USER_INPUT',
  READY_TO_DEPLOY: 'READY_TO_DEPLOY',
  DEPLOYING: 'DEPLOYING',
  DEPLOY_FAILED: 'DEPLOY_FAILED',
  DEPLOYED: 'DEPLOYED',
  VERIFYING: 'VERIFYING',
  VERIFICATION_FAILED: 'VERIFICATION_FAILED',
  VERIFIED: 'VERIFIED',
  CANCELLED: 'CANCELLED',
});

const ALLOWED_TRANSITIONS = Object.freeze({
  [DEPLOYMENT_STATES.EMPTY]: [DEPLOYMENT_STATES.REVIEWING_REQUEST],
  [DEPLOYMENT_STATES.REVIEWING_REQUEST]: [DEPLOYMENT_STATES.ASKING_CLARIFYING_QUESTION, DEPLOYMENT_STATES.READY_TO_GENERATE, DEPLOYMENT_STATES.CANCELLED],
  [DEPLOYMENT_STATES.ASKING_CLARIFYING_QUESTION]: [DEPLOYMENT_STATES.READY_TO_GENERATE, DEPLOYMENT_STATES.CANCELLED],
  [DEPLOYMENT_STATES.READY_TO_GENERATE]: [DEPLOYMENT_STATES.GENERATING, DEPLOYMENT_STATES.CANCELLED],
  [DEPLOYMENT_STATES.GENERATING]: [DEPLOYMENT_STATES.GENERATED, DEPLOYMENT_STATES.NEEDS_USER_INPUT, DEPLOYMENT_STATES.CANCELLED],
  [DEPLOYMENT_STATES.GENERATED]: [DEPLOYMENT_STATES.PREFLIGHT_RUNNING, DEPLOYMENT_STATES.CANCELLED],
  [DEPLOYMENT_STATES.PREFLIGHT_RUNNING]: [DEPLOYMENT_STATES.PREFLIGHT_FAILED, DEPLOYMENT_STATES.DRY_RUN_RUNNING, DEPLOYMENT_STATES.CANCELLED],
  [DEPLOYMENT_STATES.PREFLIGHT_FAILED]: [DEPLOYMENT_STATES.AUTO_REPAIRING, DEPLOYMENT_STATES.NEEDS_USER_INPUT, DEPLOYMENT_STATES.CANCELLED],
  [DEPLOYMENT_STATES.DRY_RUN_RUNNING]: [DEPLOYMENT_STATES.DRY_RUN_FAILED, DEPLOYMENT_STATES.READY_TO_DEPLOY, DEPLOYMENT_STATES.CANCELLED],
  [DEPLOYMENT_STATES.DRY_RUN_FAILED]: [DEPLOYMENT_STATES.AUTO_REPAIRING, DEPLOYMENT_STATES.NEEDS_USER_INPUT, DEPLOYMENT_STATES.CANCELLED],
  [DEPLOYMENT_STATES.AUTO_REPAIRING]: [DEPLOYMENT_STATES.PREFLIGHT_RUNNING, DEPLOYMENT_STATES.DRY_RUN_RUNNING, DEPLOYMENT_STATES.NEEDS_USER_INPUT, DEPLOYMENT_STATES.CANCELLED],
  [DEPLOYMENT_STATES.NEEDS_USER_INPUT]: [DEPLOYMENT_STATES.GENERATING, DEPLOYMENT_STATES.PREFLIGHT_RUNNING, DEPLOYMENT_STATES.CANCELLED],
  [DEPLOYMENT_STATES.READY_TO_DEPLOY]: [DEPLOYMENT_STATES.DEPLOYING, DEPLOYMENT_STATES.CANCELLED],
  [DEPLOYMENT_STATES.DEPLOYING]: [DEPLOYMENT_STATES.DEPLOY_FAILED, DEPLOYMENT_STATES.DEPLOYED, DEPLOYMENT_STATES.CANCELLED],
  [DEPLOYMENT_STATES.DEPLOY_FAILED]: [DEPLOYMENT_STATES.AUTO_REPAIRING, DEPLOYMENT_STATES.NEEDS_USER_INPUT, DEPLOYMENT_STATES.CANCELLED],
  [DEPLOYMENT_STATES.DEPLOYED]: [DEPLOYMENT_STATES.VERIFYING, DEPLOYMENT_STATES.VERIFIED],
  [DEPLOYMENT_STATES.VERIFYING]: [DEPLOYMENT_STATES.VERIFICATION_FAILED, DEPLOYMENT_STATES.VERIFIED],
  [DEPLOYMENT_STATES.VERIFICATION_FAILED]: [DEPLOYMENT_STATES.NEEDS_USER_INPUT, DEPLOYMENT_STATES.CANCELLED],
  [DEPLOYMENT_STATES.VERIFIED]: [],
  [DEPLOYMENT_STATES.CANCELLED]: [],
});

function assertTransition(from, to) {
  const allowed = ALLOWED_TRANSITIONS[from] || [];
  if (!allowed.includes(to)) {
    throw new Error(`Invalid deployment state transition: ${from} → ${to}`);
  }
}

function stageToState(stage, result) {
  if (result?.success && result?.realDeploy?.success) return DEPLOYMENT_STATES.DEPLOYED;
  if (result?.success && result?.readyToDeploy) return DEPLOYMENT_STATES.READY_TO_DEPLOY;
  if (result?.success && (stage === 'dryrun' || stage === 'dryrun2')) return DEPLOYMENT_STATES.READY_TO_DEPLOY;
  if (stage === 'preflight') return DEPLOYMENT_STATES.PREFLIGHT_FAILED;
  if (stage === 'dryrun' || stage === 'dryrun2') return DEPLOYMENT_STATES.DRY_RUN_FAILED;
  if (stage === 'deploy') return result?.success ? DEPLOYMENT_STATES.DEPLOYED : DEPLOYMENT_STATES.DEPLOY_FAILED;
  return result?.success ? DEPLOYMENT_STATES.READY_TO_DEPLOY : DEPLOYMENT_STATES.NEEDS_USER_INPUT;
}

module.exports = {
  DEPLOYMENT_STATES,
  ALLOWED_TRANSITIONS,
  assertTransition,
  stageToState,
};
